server:
  http_port: 8080
  grpc_port: 8081

aws:
  region: "us-west-2"
  dynamodb:
    stores_table: ""
    records_table: ""
    metadata_table: ""
  s3:
    bucket_name: ""
  elasticache:
    address: ""
    ttl: 3600
  ecr:
    repository_uri: ""
