apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-saves
  namespace: open-saves
spec:
  replicas: 2
  selector:
    matchLabels:
      app: open-saves
  template:
    metadata:
      labels:
        app: open-saves
    spec:
      serviceAccountName: open-saves-sa
      containers:
      - name: open-saves
        image: 559050240678.dkr.ecr.us-west-2.amazonaws.com/open-saves:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: grpc
        volumeMounts:
        - name: config-volume
          mountPath: /etc/open-saves
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: config-volume
        configMap:
          name: open-saves-config
