server:
  http_port: 8080
  grpc_port: 8081

aws:
  region: "us-west-2"
  dynamodb:
    stores_table: "open-saves-stores"
    records_table: "open-saves-records"
    metadata_table: "open-saves-metadata"
  s3:
    bucket_name: "open-saves-blobs-559050240678"
  elasticache:
    address: "open-saves-cache.ifdvq6.0001.usw2.cache.amazonaws.com:6379"
    ttl: 3600
